apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-orchestrator
  namespace: ml-orchestrator
spec:
  selector:
    matchLabels:
      app: ml-orchestrator
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
