apiVersion: v1
kind: Service
metadata:
  name: ml-orchestrator
  namespace: ml-orchestrator
spec:
  selector:
    app: ml-orchestrator
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
